### ISSUE TITLE
title, yes/no boxes, and some text fields gets lost between saves

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#1]
1. Create a new item. 
2. Fill in the form
3. save draft. 
4. Close window - reopen and note the temporary product doesn't have a title in the list view. When you go to edit notice that the the yes/no checkboxes don't have anything selected or some of the text fields

**Comment by lgarvey** [comment]
This is now fixed for vocab and the underlying issues have been fixed.
