### ISSUE TITLE
Creation of static pages

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#10]
Doing this currently in Markdown files.. @lgarvey  - I'm not sure what you were thinking of for stuff like additional pages - just flat html?? I guess we could use [flask-flatpages](https://pythonhosted.org/Flask-FlatPages/).. and put in a route that detects any pages not met by another route?? Or is there a better way for this??

**Comment by lgarvey** [comment]
Hey Will,

Yes, exactly that - flask-flatpages will do fine. So happy for you to build
ancillary pages in markdown/html whatever and we'll get flask-flatpages in
place.

Cheers,
Lyndon

**Comment by willwade** [comment]
Cool - for now its at https://www.dropbox.com/sh/oejgv8p9ka9f457/AABn5WL01cu5pYlY4NlUWwSba?dl=0
