### ISSUE TITLE
Search : Bug : Filters not accurate

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#102]
The feedback from Will Wade on September 7th 2015 was:

> Use fancy search. Choose a "physical device". Select "eye gaze" and Proxtalker appears. Don't get why though as it doesn't support eye gaze. whats up?

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/55033)

**Comment by raygerrard** [comment]
potential fix 434dcad4e54a6dfab66f231ea61f5b40825c8ff2

**Comment by willwade** [comment]
yep - sorted. Cheers!
