### ISSUE TITLE
temp-Other not being saved as checked on save. 

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#105]
The feedback from Will Wade on September 8th 2015 was:

> Access solutions - Typical body part : Two Others. Should be just one.

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/55216)

**Comment by willwade** [comment]
So there are two issues here. The first is that there are two "Others" in 'Typical Body Part' on access solutions. The second is that in 'Mounting options (multiple)' (in access solutions) If 'Other' is checked and text entered - it isn't being displayed on the view - or the edit. This is what it appears as if you go to edit -  ![screen shot 2015-09-08 at 09 42 34](https://cloud.githubusercontent.com/assets/229352/9730375/074ed94e-560e-11e5-8ac0-d0dd8c2083ba.png)

And then if you hit the checkbox you will find the hidden text - 
![screen shot 2015-09-08 at 09 42 44](https://cloud.githubusercontent.com/assets/229352/9730376/07558ce4-560e-11e5-872a-175f3787d8d5.png)

**Comment by raygerrard** [comment]
fixed in 6649a51ee16c3c4a9c71649701610a19e1e40af1
