### ISSUE TITLE
Revision saving problem on Pages - Staying at one version

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#106]
Following on from #98 something is still buggy...

- Go to page admin
- Edit a page which has versions (e.g /about/)
- See that there are newer  - select a version
- Hit Save & Publish
- Says its done it but actually stays on the old version

https://www.dropbox.com/s/9hmoif64888l2gt/PageRevisionSaving.mov?dl=0

**Comment by raygerrard** [comment]
fixed in b7b907bf91bc46816e8b1c4317a70ee2b6f224fb
