### ISSUE TITLE
Enhancement: User Interface: Show large view of product images / screenshots

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#108]
The feedback from Will Wade on September 10th 2015 was:

> Would be nice to click on the image and get a modal'd larger view - really useful for the videos too

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/55871)

**Comment by raygerrard** [comment]
added large image view and youtube view to product detail

1ab0a5c34dff45131d3e6bbda63bd75d67b3b157
233ae7afeeed49510447c3850811c0772ddcd31b
