### ISSUE TITLE
invalid video

### ISSUE THREAD

**Issue by raygerrard** [ACECentre/SpeechBubble#110]
http://staging.speechbubble.org.uk/products/60-picture-wordpower-phrases-and-categories-(liberator)

**Comment by willwade** [comment]
just fixed the video to something that works.. https://www.youtube.com/watch?v=8ypS-N9Bt6A but not showing? http://staging.speechbubble.org.uk/products/60-picture-wordpower-phrases-and-categories-(liberator)

**Comment by raygerrard** [comment]
this was using the share url below the video which uses a different url format, most people will likely just copy from the address bar so I have changed this in df3b86ca286eb96b8a3e0f75282ad630d961a855
