### ISSUE TITLE
Versions tab dead

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#120]
The feedback from Will Wade on September 20th 2015 was:

> Versions tab is still showing but dead?? Or should it not be at the bottom of costs & support?

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/59029)

**Comment by willwade** [comment]
NB: This is on software.

**Comment by raygerrard** [comment]
fixed in 8cc3ca47c8d7c223ed56af6b63dc69cb77eb5e7c
