### ISSUE TITLE
Product items with a slash in the title break the system

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#125]
The feedback from Will Wade on September 23rd 2015 was:

> Product items with a slash in the title break the system

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/59750)

**Comment by willwade** [comment]
So create a product e.g. "iPhone 5/5s" as the title. It kind of works (despite the _id bug) and is available from the search http://speechbubble.org.uk/products?term=iPhone%205%2F5s but you can't click on it..

**Comment by raygerrard** [comment]
fixed in https://github.com/ACECentre/SpeechBubble/issues/126
