### ISSUE TITLE
Simplified Search: Associated Devices

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#127]
Take a look at this: ![screen shot 2015-09-24 at 17 34 01](https://cloud.githubusercontent.com/assets/229352/10079573/bacdaed8-62e2-11e5-81b0-ec78203d058f.png)

Which kind of doesn't make sense since there are now quite a few software solutions that will run on that device e.g.:
http://speechbubble.org.uk/products/aac-communication-board

(Im thinking its because its looking up the associated software that is in the hardware - but for that to work we would have to add the associated software on the device each time everyone would add software.. hmmm. I'm wondering if we just remove associated software in the hardware)

**Comment by raygerrard** [comment]
fixed in 8834990cabf2308bea437ba5689c9476c0fd5d27
