### ISSUE TITLE
Search interface 

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#14]
So -  how to solve a problem like searching all of these fields. [We have a mock-up here](http://jsfiddle.net/gh/gist/jquery/1.4.4/697704fbae5f05c8f542/) but it needs testing
![screen shot 2015-01-06 at 16 13 16](https://cloud.githubusercontent.com/assets/229352/5631487/06eb321e-95bf-11e4-8a21-f77937c049aa.png)

Code here: https://gist.github.com/willwade/697704fbae5f05c8f542
Demo here: http://jsfiddle.net/gh/gist/jquery/1.4.4/697704fbae5f05c8f542/

**Comment by willwade** [comment]
Another example that I'm just leaving here for reference.. 

http://www.gettyimages.co.uk/search/2/image?phrase=cute+cats&family=creative&sort=best&excludenudity=true&page=1

![screen shot 2015-01-28 at 15 39 27](https://cloud.githubusercontent.com/assets/229352/5940620/facad8bc-a703-11e4-8d31-70d2eb4e646b.png)

**Comment by willwade** [comment]
![speechbubble search ideas continued](https://cloud.githubusercontent.com/assets/229352/6940362/0a6f2dc2-d86e-11e4-8f4d-7058efb1b7b5.png)

The trickiest part will be in that bottom access component - Ideally we would like to navigate through the access options.. But that could be difficult. In the first instance just search at Touch/Mouse/Eyegaze - exists as an option in each product category

**Comment by willwade** [comment]
The release for beta1 has taken a step back from this - so I'm going to leave this here to dwell on for beta2.

**Comment by willwade** [comment]
Would love a way, if its possible - of Bookmarking search trees. E.g. We could then shortcut to "iPad apps that are for literate users" or "Symbol based solutions that work on 10" devices"

**Comment by paulhewett** [comment]
Could you do this by reading the parameters int he qString, as per Issue 62? https://github.com/ACECentre/SpeechBubble/issues/62

**Comment by willwade** [comment]
Yeah. Think it's one of the added benefits of that. The others are for scripting the site and general usability

**Comment by willwade** [comment]
Just to clarify. It's suggested we have TWO search firms. One based on regular filters. The other that holds your hand a little.. This thread is about the latter one. Suggested that you access on initial landing page.

**Comment by paulhewett** [comment]
This got to be done this week?

**Comment by willwade** [comment]
yeah - Ray is going to *try* and do this :)

**Comment by raygerrard** [comment]
I will likely get back onto this next week I have been playing around with a few approaches but came off it to try and bring the bug list down

**Comment by willwade** [comment]
cool with me

**Comment by raygerrard** [comment]
waiting on additional feature list from @willwade

**Comment by willwade** [comment]
Y/N
- “Locked to communication software possible?”
- Environmental control possible
- Can control operating system? 
- Can control other computer ?
- Mobile phone support? 

Defining questions (if possible!!)
- Under __ kg?, 
- __ inches screen

**Comment by willwade** [comment]
Screensize - "< 10 inches screen " or " > 10 inches screen" may be better. 

Equally weight "<1kg" or "1-3kg"

**Comment by willwade** [comment]
One question. I would expect the number to go down as you go through the search flow. Is it doing an "if item exists add it to results list" rather than "if item AND item AND item exists in document then add to results list". Ie is it doing an OR rather than an AND?

**Comment by raygerrard** [comment]
yes the current search does an OR. We could not do AND because the filters apply to different products types. You would never get any results by the time you finish the search wizard.

**Comment by raygerrard** [comment]
Regarding screen size and weight filtering. I have written some current filters functionality that displays a list of tags at the top of the results page when these have been applied so the user can easily see and remove any. The problem with adding the screen size and weight filtering is that the user wont be able to see that this type of filter is also being applied and there won't be a way they can remove this. I would recommend not including this for that reason.

**Comment by raygerrard** [comment]
refactored search wizard with sketch provided by @willwade 

![image](https://cloud.githubusercontent.com/assets/1431426/8635630/6bb621ca-2824-11e5-8ef8-20e05927041a.png)
