### ISSUE TITLE
Compare feature

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#16]
This is pretty much a core requirement - as it was a big winner with the original site. But given some of our issues I think we need to schedule it a little further along the road. If we get it done earlier then yay - if not then no problem.

**Comment by lgarvey** [comment]
Hi Will,

I'll need a fuller brief.  For instance, how do we match up fields when
they might not be visible in one product, but in another.

Do we compare different types? Can you compare a vocabulary with an app
etc.?

**Comment by willwade** [comment]
Sure - I agree it needs thrashing out in detail.. I'll try and pull something together this week
