### ISSUE TITLE
AttributeError: 'module' object has no attribute 'config'

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#2]
when running locally using 

	#!/bin/bash

	SPEECHBUBBLE_MANDRILL_API_KEY=SOME_KEY 

	./manage.py runserver

and trying to register a user you get an exception:

  File "/Users/willwade/virtualenvs/SpeechBubble/lib/python2.7/site-packages/flask_security/utils.py", line 333, in send_mail
    mail.send(msg)
  File "/Users/willwade/bin/SpeechBubble/speechbubble/mail.py", line 19, in send
    from_email=app.config['MANDRILL_DEFAULT_FROM'],
AttributeError: 'module' object has no attribute 'config'

**Comment by lgarvey** [comment]
Are you still getting this?  

BTW, probably best not to put the API key in the ticket as it's public :)

**Comment by willwade** [comment]
yeah - am still getting that.. its a really odd one. I can't figure out why its not importing config

PS: Whooops!
