### ISSUE TITLE
ADD 'Objects' to Representation type to hardware. 

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#33]
- Need adding this. ? Whether needs to be added to software/vocabulary. Don't think so.

NB: remember to add to edit/display .jade files

**Comment by raygerrard** [comment]
as discussed on slack I have added the question 'Is this designed to work without software' to the vocab in the admin, added Yes/No to the detail page and by default when no filters are selected this type of vocab should not be returned in the results.
