### ISSUE TITLE
Associated Software (Hardware), Associated Vocabulary (for Software)

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#38]
So this is the software NuVoice:

http://production.speechbubble.net/products/55541a51eda50815185f78c0

And this is two of the Vocabs that run on it:

Essence: http://production.speechbubble.net/products/554b8178ab958ea36e907500
Wordpower: http://production.speechbubble.net/products/553e36ef5c4823b455925268
(there will be heaps more..)

And the software runs on these devices:
http://production.speechbubble.net/products?term=accent

So right now we have associated vocabularies in Hardware - but we also need associated Software.
We also need associated Vocabulary in Software.
And we also need associated Software in Vocabulary (right now the box is there but its showing Associated Hardware! i.e. http://production.speechbubble.net/products/554b8178ab958ea36e907500 the "Supporting Software" box should say NuVoice and the Supported Software box becomes Supported Hardware. That make sense??????

**Comment by raygerrard** [comment]
Can you break this down in terms of:

- What should related fields should be captured per product type on edit
- What should be visible in detail page by querying other products

**Comment by willwade** [comment]
Yup. That's just melted my brain. 
I've had to draw this out to remind me 
![Overview of Hardware/Software/Vocab](https://cloud.githubusercontent.com/assets/229352/7935748/01f9f350-092b-11e5-8ee9-0581d2f01246.png)
![Expanded view of Software/Vocab](https://cloud.githubusercontent.com/assets/229352/7935749/02192a0e-092b-11e5-87b5-69b5bd526626.png)

So - this is what I'm suggesting:

Hardware:
IF OS:
- Choose OS
 - Add Software (that works on that OS)

Show: Associated Software, Associated Vocabularies available.

IF No OS:
- How many Levels?
- Embed Vocabulary Options (i.e. has one type vocab so Provide 1 vocab entry - embed?)

Show: Vocabulary Options

Software:
 - Select OS
 - Add associated vocabulary (1 or more). 
 - If No associated Vocabulary, ask “how can you manage language in the software?” Provide 1 Vocab and Link (embed form?).

Show: Associated Hardware. 

Vocabulary:
 - Add associated Software 

Show:  associated software, associated hardware. 


BUT:
- It has implications for #14  - and potentially headache 'explosions' for hardware product types. 
- This is because what I'm suggesting is similar to #53  - somehow embedding the vocab options INTO software - maybe this magically becomes a new tab???

Does this make (any more) sense?!

**Comment by raygerrard** [comment]
associated functionality now in place for hardware, software and vocabularies
