### ISSUE TITLE
deleting some form elements causes system to carp

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#4]
https://github.com/ACECentre/SpeechBubble/commit/189c6b66df69e6b3fe7e8e171dfeaba84125abdb

**Comment by willwade** [comment]
To clarify - there is a bit of duplication in description. There really needs to be a title and description. Im trying to simplify a little bit by removing a second description field - we can just truncate the description for display purposes in tables etc..

**Comment by lgarvey** [comment]
Hey Will, 

Just at work but on lunch.  Just to clarify, are you saying that the description field needs removing altogether?  If so, I can do this.  

Cheers,
Lyndon

**Comment by willwade** [comment]
Kind of - each model should have a description but we can drop short_description (or description - we just need one!) - have a nice lunch :)

**Comment by lgarvey** [comment]
I have removed all the short descriptions - so now we just have name & description.  

If you have other issues removing fields, then it may be worth looking at what you're doing.  

I think as long as the fields are deleted from the forms then the edit and view pages, it should work fine.
