### ISSUE TITLE
Identify which users have helped create the content

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#41]
Need a way of showing the users involved in creating the content.

E.g. 
http://production.speechbubble.org.uk/products/55509d364594d93802320dde

"Last edited by willwade. Previous content created by RayGerrard, ERobertson and more.." (just go to two.. it could get excessive)

**Comment by raygerrard** [comment]
added basic author information to revision sidebar

**Comment by willwade** [comment]
Ray - am I being a wally - I'm not seeing that...
