### ISSUE TITLE
new product type: access solutions

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#42]
Would have:

Title: String
Description: Text
Category: Switch OR Eyegaze OR Mouse OR  Alternative/Keyboard OR 
Movement/force required: Discrete OR Gross
Output: Binary - 1 Switch, Binary - Multiple switched, Proportional 
Typical body part that controls (multiple): Hand, Eye, Head, Arm, Knee, Elbow, Muscle, Other
Cost:
Images:
Supplier:
Mounting options  (multiple): 1/4" thread, 1/8" thread, VESA, Suction, Magnets, Other (Text)
Associated Software:
Associated Hardware:
Cost: $, £ etc.

Ratings: Reliability, Ease of use, Support

Software & Hardware need to modified to allow "Particular Associated Access solutions:" which would be an associated select2 of all.. Grouped by Category. e.g..
 All Switch solutions
    Item 1
    Item 2
  All Eyegaze solutions
   Item 3
   Item 4

Could either select items individually or by category "All switch Solutions" and individual items. 
NB: It wouldn't select all Switch items - as if a new Switch item got added the product type associated items would be out of date.

**Comment by willwade** [comment]
Can we keep this out of the main search. Only if someone checks the product type ; access device in sidebar would it search for these types. Just think putting it in with all communication solutions would be confusing. It means these are items are buried a little - but it's as associated items they are important:)

**Comment by raygerrard** [comment]
this product type is now in place however there appears to be a bug in mongoose with the query to filter out the results.

I also want to thrash out the associated product bits across the board so will tackle this as a separate issue.

**Comment by raygerrard** [comment]
omitted from results unless added to filters
