### ISSUE TITLE
Glossary Items

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#43]
Need:
- A way of defining all terms that are noted across the product types. E.g.when in in edit mode - a question next to  "Battery life" - when clicked or hover presents the description in div on the page. 
- Descriptions may be variable in length. We will keep them short on the page (e.g. less than 400 chars) but in some places we may need to expand to a longer description.. 
- We would like to link to the descriptions from other places - e.g. a static page.. 

NB: #34 is a temporary solution to this.

**Comment by willwade** [comment]
Ray - I'm going to put #34 on hold.. pending your next chuck of work - hoping you may come up with a better solution!

**Comment by raygerrard** [comment]
mechanism in place, glossary content needs to grow and an list of items to be added to be created.
