### ISSUE TITLE
Enhancements to creation/revision

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#44]
I'm not sure what we can do - but this I'm getting user feedback a bit like this:

    "When you click in the search box and type in a search and click the
    magnifying glass nothing happens, you have to press enter.

    When I search for Mind Express 'Expressive' product comes up first in
    list!

    I have added ME4 product screen shot.  After saving and going back to
    edit it shows two instances of screen shot and it won't let me delete
    the second one, it says 'Image could not be deleted' when I click on the
    delete icon.  Same if I try deleting the first one.

    Now When I go into edit and try saving 'Form of representation' fields
    and 'Speech Type options' and select save draft it is not remembering
    them.  IE when I go back to edit that information is missing!

    Oh, I see now it is there where I view it as a product afterwards and
    then click edit again!  Strange.  I guess system needed time to update
    and I was being impatient perhaps!

    Was then adding Environmental control capabilities, can you have built
    in ECU in software?  SO under Additional Hardware Available I made 3
    entries and pressed Enter and lost the edit dialogue window again!

    Trying to add the ECU options but they will not stay!  The Drafts at
    bottom might be causing issue?  It keeps setting current draft to an
    earlier time one than the one that I think is the latest.

    What Am I doing wrong?  Just  tried to save support URL and I cannot do
    that either!"

I'm not sure what to do. Its a problem I think with people not realising the draft/publish process. They are checking live content and its not live. Is there someway of letting people know there maybe a more recent version waiting to be moderated/finalised in drafts and showing them the drafts??  Maybe that would help? Maybe a flag when logged in on the detail view to say "There are draft versions of this page that are waiting to be published.." Or something?

**Comment by willwade** [comment]
Django-Revisions had an interesting way of dealing with revisions. Instead of having to write a commit note it would summarise the changes made. e.g. "title changed, price ($) added.." 

Would that be possible?

**Comment by raygerrard** [comment]
I think the best approach would be to pre-populate the form with the most recent draft and have an warning that this is not published

**Comment by willwade** [comment]
That's a good idea. Would certainly help

**Comment by raygerrard** [comment]
most recent draft should be auto populated lets see how we get on with the way this works now with auto-save
