### ISSUE TITLE
Auto-save?

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#46]
A number of users are taking quite some time entering the content..
And then before they know the browser crashes or they accidentally close their browser tab.. 

I'm not sure how this would work but wondering about an auto-save..

I had another idea which may help - maybe keeping all editing above the fold by using tabs?? Not sure if a good idea or not

**Comment by raygerrard** [comment]
aded auto save for modals, if the product is saved, published or the user clicks cancel / X the auto-save is dropped. Accidentally clicking out of the modal or being logged out / refreshing the page will keep an auto-save for next edit.
