### ISSUE TITLE
auto-commit note

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#50]
Django-Revisions had an interesting way of dealing with revisions. Instead of having to write a commit note it would summarise the changes made. e.g. "title changed, price ($) added.." 

Would that be possible? May help solve some of the issues I'm seeing with folk not understanding the purpose of the commit note text field.  NB: related to #44

**Comment by raygerrard** [comment]
We are not using fixed schema definitions so this is challenging. We could provide a json diff but this would be very un-friendly. I have added a new feature to revisions which allows the user to select two revisions and then view a side-by-side comparison.

**Comment by willwade** [comment]
Yep - I can see the new method (dropping commit note entirely being part of it) solving this issue..

(Before this.. I did wonder though about using a onChange event handler on all form fields and monitoring any changes.. of course even if someone enters a field it can trigger this event handler - so not sure it would work anyways..)
