### ISSUE TITLE
Error message for not logged in user

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#51]
1. Login 
2. Create product. type type.. type stuff
3. Step away.. come back an hour later (OR: open up new tab - then logout of the site)
4. Go back to window. Press save. You get an error message "cannot save"..
Underneath the modal window you can see its gone to /login - hinting you are logged out..

- Can the error message say "You are currently logged out"?
- Is there something amiss with the cookie session time (or is there a bug with passport?)?

NB: associated with #46

**Comment by raygerrard** [comment]
you should remain logged in for the entire browser session, unless you clear your cookies / logout from another tab.

**Comment by willwade** [comment]
Is there anyway the session is timing out Ray? I'm wondering if there is something astray - seen it a couple of times with other folk ..might be something we just need to look a bit more indepth when/if it happens again....

**Comment by raygerrard** [comment]
Have checked my cookies and definitely no timeout on the token. I have added a popup window with: 'You are currently logged out. Please login.' 

If this happens again please re-raise with as much info as you can regarding steps to replicate / browser / time left etc.
