### ISSUE TITLE
User feedback on new features/bugs/issues

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#52]
Need a really nice easy way of getting user feedback on all aspects of the site.. 

Contemplating [UserVoice](https://www.uservoice.com)  for this. Just got to work out costs. Any better ideas?

**Comment by willwade** [comment]
Uservoice is great - but it's pricey. Doorbell.io may be more suitable.. Slimmer, Has an api or embed code: https://doorbell.io/docs/api & https://gist.github.com/willwade/2f6e69d225ce721d044b

**Comment by paulhewett** [comment]
Suggest 'New Product' button on login rather than having to go into Product Administration. Suggest add menu item 'Add Product' to Product menu

**Comment by paulhewett** [comment]
Admin Menu children use word 'moderation', pages use 'administration'. Suggest consistent use of 'Administration' or 'Admin'

**Comment by paulhewett** [comment]
Prefer sentence case in high level menus, 'User Moderation' rather than 'User moderation'

**Comment by paulhewett** [comment]
Prefer clickable are in main nav to be li rather than a to give larger click area

**Comment by paulhewett** [comment]
Home icon too small, increase size or increase size of clickable area

**Comment by raygerrard** [comment]
add to index
