### ISSUE TITLE
Tidy up of Software: One Vocabulary

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#53]
A lot of apps have only one Vocabulary.

Take for example SpeakForYourself:

This is the app: http://production.speechbubble.org.uk/products/5565853f49d5e434020f06e1
This is the Vocab: http://production.speechbubble.org.uk/products/5565863d49d5e434020f0705

Confused!?

Its because the app doesn't really have a Vocab - the App itself is the vocab. So some ideas to solve this:

If One Vocab: Merge the two views.. This of course could make our specific search (Vocabulary and Software) a bit of a headache..

(More ideas to follow..)

**Comment by raygerrard** [comment]
If the app has its own vocab should this be considered a distinct vocab? Would it not be more appropriate to have a field on the software product that captures some details about built-in vocab

**Comment by raygerrard** [comment]
nested vocabulary view inside hardware view when only a single associated vocabulary is related

**Comment by willwade** [comment]
its fab for hardware.. is it possible ray to do the same for software. i.e. if software has one vocabulary merge it into the software view and hide the vocab from search?

**Comment by raygerrard** [comment]
I have added the embedded vocabulary to software view as well

**Comment by willwade** [comment]
blimey you are quick :)

**Comment by raygerrard** [comment]
we wouldn't be able to hide the vocabulary from the search results based on this though

**Comment by willwade** [comment]
thats ok .... the aim of  #14 would be to compile this all nicely... hopefully that may do the trick
