### ISSUE TITLE
UnauthorizedHeader

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#54]
I note in a few emails from folk trying to upload images that they are having some difficulty in deleting images and occasionally uploading..

Can't quite get to the bottom of it but I wonder if its to do with this that I'm seeing in the logs:

May 26 14:42:46 lisa speechbubble:  #033[90mGET /api/feeds/twitter?limit=3 #033[32m200 #033[90m481ms#033[0m
May 26 14:42:46 lisa speechbubble:  URL [https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=acecentre&count=3]
May 26 14:42:46 lisa speechbubble:  #033[90mGET /api/feeds/twitter?limit=3 #033[32m200 #033[90m501ms#033[0m
May 26 14:43:02 lisa speechbubble:  UnauthorizedError: No Authorization header was found
May 26 14:43:02 lisa speechbubble:  #033[90mPOST /api/product/upload/5564783549d5e434020f02a2 #033[33m401 #033[90m22ms - 12b#033[0m
May 26 14:43:55 lisa speechbubble:  UnauthorizedError: No Authorization header was found
May 26 14:43:55 lisa speechbubble:  #033[90mPOST /api/product/upload/5564783549d5e434020f02a2 #033[33m401 #033[90m15ms - 12b#033[0m
May 26 14:44:19 lisa speechbubble:  UnauthorizedError: No Authorization header was found
May 26 14:44:19 lisa speechbubble:  #033[90mPOST /api/product/upload/5564783549d5e434020f02a2 #033[33m401 #033[90m8ms - 12b#033[0m
May 26 14:44:28 lisa speechbubble:  UnauthorizedError: No Authorization header was found

**Comment by raygerrard** [comment]
this looks as though the user had lost their session for one reason or another before trying to upload or delete which is restricted to logged in users. We now have the login notifications on products when this occurs so the user should get a notification to login if this is the case. I have tested and have been able to add and delete images locally and received the login notification when clearing cookies and attempting an upload.
