### ISSUE TITLE
Disqus: SSO

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#60]
Is it possible to link the SpeechBubble login with Disqus @raygerrard ?? E.g https://help.disqus.com/customer/portal/articles/236206-single-sign-on

**Comment by raygerrard** [comment]
Can you request this feature be enabled on your account here:

http://disqus.com/support/?article=contact_SSO

**Comment by willwade** [comment]
Contacted Disqus :8ball:

**Comment by willwade** [comment]
Enabled
"Hi SpeechBubbleWeb,

Thanks for reaching out.

We’ve gone ahead and activated SSO for your account and this enables SSO for all forums for which you are primary moderator. Please note that this feature is provided free of charge.

To get started, we’ve provided links to our installation documentation below.

Note that our documentation is written as a technical development resource and should be implemented by developers well-familiarized with concepts such as API applications, public and secret keys, HMAC, Base64-encoding, and JSON-encoding.

Getting started:
http://help.disqus.com/customer/portal/articles/684744-getting-started-with-single-sign-on
Creating an API application:
http://help.disqus.com/customer/portal/articles/787016-how-to-create-an-api-application
Installing on WordPress:
http://help.disqus.com/customer/portal/articles/1148635-setting-up-sso-on-wordpress

Note that in some cases, it can take 24 hours or longer for an SSO domain to become available for users to be created. See our debugging steps here: http://help.disqus.com/customer/portal/articles/1148640-sso-debug-checklist

If you have any additional questions, feel free to visit our developer forum for additional assistance from our team and community: https://groups.google.com/forum/?fromgroups#!forum/disqus-dev – please include that we sent you in your forum post along with a link to your site and the details of the issue."

**Comment by raygerrard** [comment]
can you look at configuring the remote domain and creating the api application and then pass your details over to me securely outside of github. 

More details are here:

https://help.disqus.com/customer/portal/articles/236206#configure-domain

**Comment by raygerrard** [comment]
sso should now be in place. Please add the disqus environment variables to the server:

DISQUS_PUBLIC -> API_KEY
DISQUS_SECRET -> API_SECRET

**Comment by willwade** [comment]
ok added this - just need five minutes to check all working

**Comment by raygerrard** [comment]
testing in prod closing
