### ISSUE TITLE
Disqus: Moderation on new items

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#61]
Is it possible to set all comments to be moderated? Or maybe a way of us turning on/off moderation of comments for each page? NB: I'm not sure whether we do want to have everything moderated - it may be a headache. Disqus works nicely as members can flag it.. More of a question at this stage.

**Comment by willwade** [comment]
On reading the BBC news pages I note they have this line before their comments which may be worth copying if we can "all posts are reactively-moderated and must obey the house rules."

**Comment by raygerrard** [comment]
You should be able to moderate comments through the disqus dashboard, from reading the embed documentation there doesn't appear to be a javascript configureable for page by page moderation setting: https://help.disqus.com/customer/portal/articles/472098

please see here for more info on moderating comments: https://help.disqus.com/customer/portal/articles/466238-moderating-your-community

I have added some small print as mentioned above to comments
