### ISSUE TITLE
Content on some pages forces main content column marginally wider

### ISSUE THREAD

**Issue by paulhewett** [ACECentre/SpeechBubble#63]
This is really picky I know, sorry guys! On some pages the content column is forced slightly wider, eg. transition between Home and View all Products.

It's only a few pixels I know but...

**Comment by raygerrard** [comment]
I can't replicate this issue.

Can you send over browser details / screen shots?

**Comment by paulhewett** [comment]
https://www.dropbox.com/s/2em0hm03du8cfig/Speech%20Bubble%20Jiggle.mp4?dl=0

**Comment by paulhewett** [comment]
![screenshot 2015-06-05 14 35 14](https://cloud.githubusercontent.com/assets/2620062/8006947/2308b1a0-0b90-11e5-9cf0-b7a8a3cfcfe7.png)

**Comment by raygerrard** [comment]
this is due to the homepage not having a scrollbar visible on the homepage as the page content is less than the window height. I have added some css to ensure there is always a scrollbar present.
