### ISSUE TITLE
Logged in home should be different to logged out home

### ISSUE THREAD

**Issue by paulhewett** [ACECentre/SpeechBubble#64]
Content on home page is perhaps more useful when it is different once you've logged in. If you're logged out, might be a new user etc, want to give them an introduction about the site etc.

If you're logged in, you're probably going to add or edit something. You might want to 'Add Product', see you last five edited products: some CTA's to easily direct people to the task they might want to do (which I think is different to a casual browser).

**Comment by paulhewett** [comment]
If this is agreed, I'm happy to suggest some content

**Comment by willwade** [comment]
Go ahead and suggest some content! :)

**Comment by raygerrard** [comment]
any pointers to what we want to add for this?

**Comment by willwade** [comment]
Here's some ideas:
- Your edits in most recent order. Mark which ones have been published or not
- Your comments and mark any replies (no idea if that will be possible)
- Maybe most recently viewed items?? Is that even possible Ray?!

@paulhewett  - did you have any other bright ideas?!

**Comment by willwade** [comment]
Also wondering about a Link to "Create new Product.." yes - its in the dropdown but making it more obvious..

Also - a link to edit your profile..

**Comment by paulhewett** [comment]
Keep it simple bearing in mind time remaining:

Two big square buttons that take up a big chunk of the page
NEW PRODUCT
NEW SUPPLIER

Unpublished Products
Products awaiting moderation

**Comment by raygerrard** [comment]
added recent updated products, your recently viewed products and recent product contributions with cta when none are available
