### ISSUE TITLE
Product editor form should be modal

### ISSUE THREAD

**Issue by paulhewett** [ACECentre/SpeechBubble#65]
Although this form does auto save, it is distracting that it's disappeared. I think this should be modal (though you would currently have to scroll right down to close or save), or capture an event when user clicks off the form to create a modal dialog with Save/Close option

**Comment by paulhewett** [comment]
When editing a product from here http://production.speechbubble.org.uk/admin/products, it is modal.

When clicking edit on the product's page, eg. here, http://production.speechbubble.org.uk/products/tobii-i-12, it's not modal - you can click off the form and disappears.

**Comment by willwade** [comment]
Ah gotcha ! That explains how it's happened recently to others. Nice one. Good find!

**Comment by raygerrard** [comment]
prevent from closing when accidentally clicking outside modal window, auto-save still in place for disconnect / refresh.
