### ISSUE TITLE
Product form help tips required

### ISSUE THREAD

**Issue by paulhewett** [ACECentre/SpeechBubble#66]
I think all items should have a least some explanation. In particular required on:

Hardware locked to communication software
Guide price (including tax?)

**Comment by willwade** [comment]
Yep: see https://github.com/ACECentre/SpeechBubble/issues/43#issuecomment-106931545

Can you pop in this page any missing items and we (someone!) will get round to adding them to the Glossary..  OR add them to http://production.speechbubble.org.uk/admin/glossary and jot down the added bits here..

**Comment by willwade** [comment]
Please update the wiki entry @paulhewett instead of this page.. will be easier to update :) https://github.com/ACECentre/SpeechBubble/wiki/Glossary-items-to-do
