### ISSUE TITLE
What to do about large volume of checkboxes

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#7]
Not sure how we deal with this little UI issue

![screen shot 2015-01-06 at 13 04 04](https://cloud.githubusercontent.com/assets/229352/5628861/94bb55c6-95a4-11e4-9b4b-5f63d77a5f31.png)

**Comment by willwade** [comment]
@lgarvey  - what do you think to some of these checkboxes being turned into multi-selects then using the design pattern under [multiple select boxes](https://select2.github.io/examples.html) (second one down)? What do you think?

**Comment by lgarvey** [comment]
Would you want all checkboxes turning into multi selects?

**Comment by willwade** [comment]
Hmm - well call me cautious but don't think so. It may work for all but I'm thinking this design pattern may be bad for all..  can't work out why though
