### ISSUE TITLE
View all products pagination enhancement

### ISSUE THREAD

**Issue by paulhewett** [ACECentre/SpeechBubble#70]
Search is great, and it's slick how adding criteria reduces results. Fine.

If I'm looking for a Tobii i-12, through 'view all products' it can be tricky. If I enter i12, I can't find it, if I enter i-12 I will. It will come up if I search for Tobii.

If I'm looking for Alphaboard, it won't be found if I enter alpha. I use this one as I can never remember how proloquo2go is spelt. If I'm looking for some info on this, I might try prolo, etc. But it would not be found unless I spelt the complete word correctly.

With these examples, I would have to guess which page it's on, and use the pagination with a bit of trial and error until I found the right page.

I wonder if it might be worth enhancing the pagination. For example by having an alphabetical alternative, eg. | A | B | C | D etc, or including including the letters included in the pagination, eg. | 1 (aa - ac) | 2 (ad - be) | 3 (bo - de)...

I know it get's a bit messy, but something to help find the result you're looking for if you're hunting for a particular bit of kit or software and can't quite remember exactly what it's called.

**Comment by raygerrard** [comment]
unfortunetly mongodb doesnt support search in this way, if you were to search for thing you would get results containing thing, thing's etc but th will not return those.

I am not sold on the idea of alphabetical pagination but I can see the point you raise of finding what you are looking for if you have a specific product in mind. For this I have added auto-complete functionality to the main header so you will be given a suggestions of a specific product if it finds similar on keyup.

Hopefully this sorts the problem out, let me know if you have any other ideas on improving this.
