### ISSUE TITLE
Access solution changes

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#72]
1. Need to fix this typo
![screen shot 2015-06-08 at 16 11 21](https://cloud.githubusercontent.com/assets/229352/8038054/26a2295c-0df9-11e5-9702-d9ea02be00dd.png)

So should be a space between Access and Solution "Access Solution"

2. Change "Category" to "Input required"

and then change options to radio buttons of:

Eye movement
Body movement - Discrete
Body movement - Gross

3. Change "Output" options:

Binary - 1 Switch
Binary  - 2 or more switches
Proportional

4. Computer control options:

(checklist of options - Multiple allowed)
Keyboard
  IF Y: Ask "Is additional software required to make this work?"
  IF Y: Ask "Wired or Wireless?" (option)
Mouse
  IF Y: Ask "Is additional software required to make this work?"
   IF Y: Ask "Wired or Wireless?" (option)

4.  Mounting options:
 Add "Standalone"

5. Remove "Ready-made vocabularies"

**Comment by willwade** [comment]
sorry @raygerrard - don't fret about losing data for these changes :)

**Comment by raygerrard** [comment]
changes made to admin and detail views
