### ISSUE TITLE
Content: Adding detail to verfication process required

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#74]
The feedback from Will Wade on June 10th 2015 was:

> This page needs some tarting up - along with the emails.. A job for will

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/25106)

All emails need overhauling with content and grammar. 
Verification page require Information on next steps now verfied. See also @paulhewett comments on landing pages #64

**Comment by raygerrard** [comment]
I have created a custom speech bubble email layout for signup and admin emails. I have also added some copy to the verification page with a link to search.
