### ISSUE TITLE
Product edit tabbed interface

### ISSUE THREAD

**Issue by raygerrard** [ACECentre/SpeechBubble#75]
Please comment if you have any suggestions / preference to tabs names / fields in each tab etc

**Comment by willwade** [comment]
for the record.. 
![screen_shot_2015-05-28_at_22 16 16](https://cloud.githubusercontent.com/assets/229352/8202466/1e8a8176-14d2-11e5-9034-fc7ae2073ea5.png)

**Comment by willwade** [comment]
My feeling is they need to be some standardisation between all types.. it may mean moving some bits around though depending on the product type. So Hardware:

1. Basic (maybe "Essential") details (as Step 1 but also add Images and Videos)
2. Technical (Ready Made vocabs.. through to Mobile phone capabilities..also dimensions and battery life)
3. Costs (Price and warranty)
4. Access & Extras (Access methods, Enviro Control, Mobile phone, Mounting, More info)

Im guessing the commit note stuff now not needed...

Software:
1. Essential (See above)
2. Technical (forrm of representation and Speech type, Supported devices, Operating Systems, Ready Made vocabularies)
3. Costs (Price and associated costs)
4. Access & extras (Enviro Control, Can control a separate device, Can control a OS, Support URLs, Access methods)

Vocabulary:
1. Essential
2. Technical (this ends up being shorter than the rest.. but can expand quite deep..)
3. Costs
4. Access & Extras

Access:
1. Essential (See above)
2. Technical (All other bits! - this may be a bit long..) 
3. Costs (Guide price and associated costs)

**Comment by paulhewett** [comment]
The list I wrote just now for Hardware (before seeing yours Will) was very similar! I had:

HARDWARE
1. Basic Information (Name, Description, Discontinued, Product Images, Videos, More Information URLS)
2. Features (Vocabularies, Associated Software, OS, Phone Capabilities, Mounting, EC, Access)
3. [Physical] Specification (Dimensions, Battery)
4. Pricing and Support (Suppliers, Guide Price, Associated Costs, Support and Warranty)

I've deliberately put them in that order too. I think pricing should come last - features are key I think.


ACCESS
1. Basic Information (as above)
2. Features (Input reqd, Output, Computer control, body part, mounting options)
3. Pricing and Support ( as above)

SOFTWARE PRODUCT
1. Basic Information
2. Features (Form of.., Speech type, EC, Software can.., Editing options, Visual options, Supported devices, OS, Access methods)
3. Pricing and Support

LOW TECH
1. Basic Information
2. Features (Form of.., Access method)
3. Pricing and Support

VOCABULARY
1. Basic Information
2. Features (Work without..., Presented, Access method,)
3. Pricing and Support

**Comment by willwade** [comment]
Yeah - v similar.. ray - the choice is yours.. I'll let you have the casting vote!

**Comment by raygerrard** [comment]
merged the two and added to it a bit
