### ISSUE TITLE
Ready-made vocabularies : No - Provide creation of vocabulary option

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#78]
In hardware and software...
Ready-made vocabularies :  No / Yes..

IF Hit  No then  give user  a link to make  a  vocabulary with “If  you would like to define a way of this device can organise vocabulary click here”
which basically links to the same thing in “Available Vocabularies ‘Create a new vocaulary’” - This defines there will only be one vocab associated with it..  

![screen shot 2015-06-17 at 22 17 04](https://cloud.githubusercontent.com/assets/229352/8219071/63a20bae-153f-11e5-9cfd-f7623c1d6dfa.png)

**Comment by raygerrard** [comment]
this is done
