### ISSUE TITLE
Content only viewable if logged in

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#82]
The feedback from Will Wade on June 19th 2015 was:

> Can't view content if not logged in

View it on [Doorbell](https://doorbell.io/applications/1028/feedback/32486)

**Comment by raygerrard** [comment]
what content is this?

**Comment by willwade** [comment]
Go to production. Select view all. Hit one of the items (actually a software) :)

**Comment by raygerrard** [comment]
fixed
