### ISSUE TITLE
If admin - provide delete from Edit screen

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#85]
Was this ever there Ray or did we lose it in the shift to tabs?

**Comment by raygerrard** [comment]
you should be able to delete revisions from the versions tab in the edit screen, this is only visible if 2 or more versions are present. 

To delete an entire product you can do this from the product admin listing.

**Comment by willwade** [comment]
Ahh the problem is finding it in the products list. You used to be able to search for a product name in admin moderation screen but now searching with that pushes you to the non-admin product list. So a bit tricky now with 300 odd products.

**Comment by raygerrard** [comment]
added search to the product admin sidebar
