### ISSUE TITLE
Double modal window bug

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#88]
Create Software -> Create a vocabulary from the software.. You get so far but the modal window tabs don't work. 

See around 1:12 of this: https://www.dropbox.com/s/7zjre07e6a74tr7/BugsWithModal.mov?dl=0

**Comment by willwade** [comment]
its not a bug with IE 8. Its actually a bug with regular no-scrolly mice. The only way to scroll up and down is to use a scrolly mouse - or touchpad and use a gesture - or iPad.. No idea what the solution would be :$

**Comment by raygerrard** [comment]
fixed in abdd57795fd555d62a299d1fc617064451f08c37
