### ISSUE TITLE
emails not picking up attached images.. 

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#93]
In Email.jade we have:

``                                    img(src='#{domain}/assets/images/emails/email-header.gif', alt='', border='0', hspace='0', vspace='0', width='600', height='151', style='display:block; line-height: 0')``

But the image on the server is: 8f8435d8.email-header.gif

So its 404'ing when the email client tries to get that image.. Maybe CSS too.

I'm guessing this is a grunt/yeoman thing?

**Comment by willwade** [comment]
A rather temporary fix: https://github.com/ACECentre/SpeechBubble/commit/56b6ca9c07aa7b991e5cb17b234150c8a98cf51f

**Comment by willwade** [comment]
Fix didn't work. I'm guessing we need to tweak Gruntfile.js

**Comment by raygerrard** [comment]
this is due to a grunt task `rev` which is used for cache busting. server-side template rendering is not rev'd and the documentation doesn't have any details regarding ignoring specific files. I have removed this step from the build.
