### ISSUE TITLE
Search causing crash.

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#95]
The wizard search is causing a major crash of the server..

[Here](https://gist.githubusercontent.com/willwade/b8175fef1b6b235e12d9/raw/cf5965c6c0a6c8371c348952074f8b180665c8ef/error.log) is the log.

I'm wondering if this was due to the last two changes to the repo e.g. https://github.com/ACECentre/SpeechBubble/commit/e484478751431777209beed82be16e1ada50d8df

**Comment by raygerrard** [comment]
added item check to associated reduce function return statement 7c643cb7b622298ec558d960f20e48680ea66d1f
