### ISSUE TITLE
entity too large error

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#97]
Log [here](https://gist.githubusercontent.com/willwade/54104ddedc60c5b53ad0/raw/3c1ed32bc669bb4068e6f70d612399315fcdd25f/error-entity-too-large.log).

 this happened when trying to create a software product..  
just getting a standard error to the user that can't save product..

![screen shot 2015-07-29 at 18 18 47](https://cloud.githubusercontent.com/assets/229352/8964581/45f909e0-361e-11e5-9b24-ef831658a45c.png)

**Comment by raygerrard** [comment]
fixed in fff8855d13aca02d92e1aae095eecda508034a10
