### ISSUE TITLE
problem publishing revision

### ISSUE THREAD

**Issue by willwade** [ACECentre/SpeechBubble#98]
Sep 02 23:54:30 lisa speechbubble:  #033[90mGET /api/page/5511696c53ef06a0113e0de8/revisions #033[32m200 #033[90m42ms#033[0m
Sep 02 23:55:05 lisa speechbubble:  #033[90mPOST /api/page/publish/5511696c53ef06a0113e0de8/undefined #033[33m404 #033[90m13ms - 9b#033[0m

See video: https://www.dropbox.com/s/jazvl4s30npxni1/PageCreationProblem.mov?dl=0

**Comment by raygerrard** [comment]
fixed in 96e636465e0591b05a07e9d2431d2ce417e34737
